//#pragma warning disable 1591
////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.42000
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace CSTest._21_Database._03_LinqToSql
//{
//	using System.Data.Linq;
//	using System.Data.Linq.Mapping;
//	using System.Data;
//	using System.Collections.Generic;
//	using System.Reflection;
//	using System.Linq;
//	using System.Linq.Expressions;
//	using System.ComponentModel;
//	using System;
	
	
//	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShopDB")]
//	public partial class ShopDBDataContext : System.Data.Linq.DataContext
//	{
		
//		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
//    #region Extensibility Method Definitions
//    partial void OnCreated();
//    partial void InsertCUSTOMER(CUSTOMER instance);
//    partial void UpdateCUSTOMER(CUSTOMER instance);
//    partial void DeleteCUSTOMER(CUSTOMER instance);
//    partial void InsertSALESREP(SALESREP instance);
//    partial void UpdateSALESREP(SALESREP instance);
//    partial void DeleteSALESREP(SALESREP instance);
//    partial void InsertOFFICE(OFFICE instance);
//    partial void UpdateOFFICE(OFFICE instance);
//    partial void DeleteOFFICE(OFFICE instance);
//    partial void InsertORDER(ORDER instance);
//    partial void UpdateORDER(ORDER instance);
//    partial void DeleteORDER(ORDER instance);
//    partial void InsertPRODUCT(PRODUCT instance);
//    partial void UpdatePRODUCT(PRODUCT instance);
//    partial void DeletePRODUCT(PRODUCT instance);
//    #endregion
		
//		public ShopDBDataContext() : 
//				base(global::CSTest.Properties.Settings.Default.ShopDBConnectionString, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public ShopDBDataContext(string connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public ShopDBDataContext(System.Data.IDbConnection connection) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public ShopDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public ShopDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//				base(connection, mappingSource)
//		{
//			OnCreated();
//		}
		
//		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
//		{
//			get
//			{
//				return this.GetTable<CUSTOMER>();
//			}
//		}
		
//		public System.Data.Linq.Table<SALESREP> SALESREPs
//		{
//			get
//			{
//				return this.GetTable<SALESREP>();
//			}
//		}
		
//		public System.Data.Linq.Table<OFFICE> OFFICEs
//		{
//			get
//			{
//				return this.GetTable<OFFICE>();
//			}
//		}
		
//		public System.Data.Linq.Table<ORDER> ORDERs
//		{
//			get
//			{
//				return this.GetTable<ORDER>();
//			}
//		}
		
//		public System.Data.Linq.Table<PRODUCT> PRODUCTs
//		{
//			get
//			{
//				return this.GetTable<PRODUCT>();
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCustomerByName")]
//		public ISingleResult<spCustomerByNameResult> spCustomerByName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(25)")] string company)
//		{
//			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), company);
//			return ((ISingleResult<spCustomerByNameResult>)(result.ReturnValue));
//		}
		
//		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCustomerById")]
//		public int spCustomerById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(25)")] ref string company, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Limit", DbType="Decimal(18,0)")] ref System.Nullable<decimal> limit)
//		{
//			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, company, limit);
//			company = ((string)(result.GetParameterValue(1)));
//			limit = ((System.Nullable<decimal>)(result.GetParameterValue(2)));
//			return ((int)(result.ReturnValue));
//		}
		
//		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCustomerByName2")]
//		public ISingleResult<spCustomerByName2Result> spCustomerByName2([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(25)")] string company)
//		{
//			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), company);
//			return ((ISingleResult<spCustomerByName2Result>)(result.ReturnValue));
//		}
		
//		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sfCustomerCompanyById", IsComposable=true)]
//		public string sfCustomerCompanyById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
//		{
//			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
//		}
		
//		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sfCustomerInfoById", IsComposable=true)]
//		public IQueryable<sfCustomerInfoByIdResult> sfCustomerInfoById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id", DbType="Int")] System.Nullable<int> id)
//		{
//			return this.CreateMethodCallQuery<sfCustomerInfoByIdResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMERS")]
//	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _CUST_NUM;
		
//		private string _COMPANY;
		
//		private System.Nullable<int> _CUST_REP;
		
//		private System.Nullable<decimal> _CREDIT_LIMIT;
		
//		private EntitySet<ORDER> _ORDERs;
		
//		private EntityRef<SALESREP> _SALESREP;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnCUST_NUMChanging(int value);
//    partial void OnCUST_NUMChanged();
//    partial void OnCOMPANYChanging(string value);
//    partial void OnCOMPANYChanged();
//    partial void OnCUST_REPChanging(System.Nullable<int> value);
//    partial void OnCUST_REPChanged();
//    partial void OnCREDIT_LIMITChanging(System.Nullable<decimal> value);
//    partial void OnCREDIT_LIMITChanged();
//    #endregion
		
//		public CUSTOMER()
//		{
//			this._ORDERs = new EntitySet<ORDER>(new Action<ORDER>(this.attach_ORDERs), new Action<ORDER>(this.detach_ORDERs));
//			this._SALESREP = default(EntityRef<SALESREP>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
//		public int CUST_NUM
//		{
//			get
//			{
//				return this._CUST_NUM;
//			}
//			set
//			{
//				if ((this._CUST_NUM != value))
//				{
//					this.OnCUST_NUMChanging(value);
//					this.SendPropertyChanging();
//					this._CUST_NUM = value;
//					this.SendPropertyChanged("CUST_NUM");
//					this.OnCUST_NUMChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
//		public string COMPANY
//		{
//			get
//			{
//				return this._COMPANY;
//			}
//			set
//			{
//				if ((this._COMPANY != value))
//				{
//					this.OnCOMPANYChanging(value);
//					this.SendPropertyChanging();
//					this._COMPANY = value;
//					this.SendPropertyChanged("COMPANY");
//					this.OnCOMPANYChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REP", DbType="Int")]
//		public System.Nullable<int> CUST_REP
//		{
//			get
//			{
//				return this._CUST_REP;
//			}
//			set
//			{
//				if ((this._CUST_REP != value))
//				{
//					if (this._SALESREP.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnCUST_REPChanging(value);
//					this.SendPropertyChanging();
//					this._CUST_REP = value;
//					this.SendPropertyChanged("CUST_REP");
//					this.OnCUST_REPChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDIT_LIMIT", DbType="Money")]
//		public System.Nullable<decimal> CREDIT_LIMIT
//		{
//			get
//			{
//				return this._CREDIT_LIMIT;
//			}
//			set
//			{
//				if ((this._CREDIT_LIMIT != value))
//				{
//					this.OnCREDIT_LIMITChanging(value);
//					this.SendPropertyChanging();
//					this._CREDIT_LIMIT = value;
//					this.SendPropertyChanged("CREDIT_LIMIT");
//					this.OnCREDIT_LIMITChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_ORDER", Storage="_ORDERs", ThisKey="CUST_NUM", OtherKey="CUST")]
//		public EntitySet<ORDER> ORDERs
//		{
//			get
//			{
//				return this._ORDERs;
//			}
//			set
//			{
//				this._ORDERs.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_CUSTOMER", Storage="_SALESREP", ThisKey="CUST_REP", OtherKey="EMPL_NUM", IsForeignKey=true, DeleteRule="SET NULL")]
//		public SALESREP SALESREP
//		{
//			get
//			{
//				return this._SALESREP.Entity;
//			}
//			set
//			{
//				SALESREP previousValue = this._SALESREP.Entity;
//				if (((previousValue != value) 
//							|| (this._SALESREP.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._SALESREP.Entity = null;
//						previousValue.CUSTOMERs.Remove(this);
//					}
//					this._SALESREP.Entity = value;
//					if ((value != null))
//					{
//						value.CUSTOMERs.Add(this);
//						this._CUST_REP = value.EMPL_NUM;
//					}
//					else
//					{
//						this._CUST_REP = default(Nullable<int>);
//					}
//					this.SendPropertyChanged("SALESREP");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_ORDERs(ORDER entity)
//		{
//			this.SendPropertyChanging();
//			entity.CUSTOMER = this;
//		}
		
//		private void detach_ORDERs(ORDER entity)
//		{
//			this.SendPropertyChanging();
//			entity.CUSTOMER = null;
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALESREPS")]
//	public partial class SALESREP : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _EMPL_NUM;
		
//		private string _NAME;
		
//		private System.Nullable<int> _AGE;
		
//		private System.Nullable<int> _REP_OFFICE;
		
//		private string _TITLE;
		
//		private System.DateTime _HIRE_DATE;
		
//		private System.Nullable<int> _MANAGER;
		
//		private System.Nullable<decimal> _QUOTA;
		
//		private decimal _SALES;
		
//		private EntitySet<CUSTOMER> _CUSTOMERs;
		
//		private EntitySet<SALESREP> _SALESREPs;
		
//		private EntitySet<OFFICE> _OFFICEs;
		
//		private EntitySet<ORDER> _ORDERs;
		
//		private EntityRef<SALESREP> _SALESREP1;
		
//		private EntityRef<OFFICE> _OFFICE;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnEMPL_NUMChanging(int value);
//    partial void OnEMPL_NUMChanged();
//    partial void OnNAMEChanging(string value);
//    partial void OnNAMEChanged();
//    partial void OnAGEChanging(System.Nullable<int> value);
//    partial void OnAGEChanged();
//    partial void OnREP_OFFICEChanging(System.Nullable<int> value);
//    partial void OnREP_OFFICEChanged();
//    partial void OnTITLEChanging(string value);
//    partial void OnTITLEChanged();
//    partial void OnHIRE_DATEChanging(System.DateTime value);
//    partial void OnHIRE_DATEChanged();
//    partial void OnMANAGERChanging(System.Nullable<int> value);
//    partial void OnMANAGERChanged();
//    partial void OnQUOTAChanging(System.Nullable<decimal> value);
//    partial void OnQUOTAChanged();
//    partial void OnSALESChanging(decimal value);
//    partial void OnSALESChanged();
//    #endregion
		
//		public SALESREP()
//		{
//			this._CUSTOMERs = new EntitySet<CUSTOMER>(new Action<CUSTOMER>(this.attach_CUSTOMERs), new Action<CUSTOMER>(this.detach_CUSTOMERs));
//			this._SALESREPs = new EntitySet<SALESREP>(new Action<SALESREP>(this.attach_SALESREPs), new Action<SALESREP>(this.detach_SALESREPs));
//			this._OFFICEs = new EntitySet<OFFICE>(new Action<OFFICE>(this.attach_OFFICEs), new Action<OFFICE>(this.detach_OFFICEs));
//			this._ORDERs = new EntitySet<ORDER>(new Action<ORDER>(this.attach_ORDERs), new Action<ORDER>(this.detach_ORDERs));
//			this._SALESREP1 = default(EntityRef<SALESREP>);
//			this._OFFICE = default(EntityRef<OFFICE>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPL_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
//		public int EMPL_NUM
//		{
//			get
//			{
//				return this._EMPL_NUM;
//			}
//			set
//			{
//				if ((this._EMPL_NUM != value))
//				{
//					this.OnEMPL_NUMChanging(value);
//					this.SendPropertyChanging();
//					this._EMPL_NUM = value;
//					this.SendPropertyChanged("EMPL_NUM");
//					this.OnEMPL_NUMChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
//		public string NAME
//		{
//			get
//			{
//				return this._NAME;
//			}
//			set
//			{
//				if ((this._NAME != value))
//				{
//					this.OnNAMEChanging(value);
//					this.SendPropertyChanging();
//					this._NAME = value;
//					this.SendPropertyChanged("NAME");
//					this.OnNAMEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
//		public System.Nullable<int> AGE
//		{
//			get
//			{
//				return this._AGE;
//			}
//			set
//			{
//				if ((this._AGE != value))
//				{
//					this.OnAGEChanging(value);
//					this.SendPropertyChanging();
//					this._AGE = value;
//					this.SendPropertyChanged("AGE");
//					this.OnAGEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REP_OFFICE", DbType="Int")]
//		public System.Nullable<int> REP_OFFICE
//		{
//			get
//			{
//				return this._REP_OFFICE;
//			}
//			set
//			{
//				if ((this._REP_OFFICE != value))
//				{
//					if (this._OFFICE.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnREP_OFFICEChanging(value);
//					this.SendPropertyChanging();
//					this._REP_OFFICE = value;
//					this.SendPropertyChanged("REP_OFFICE");
//					this.OnREP_OFFICEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(10)")]
//		public string TITLE
//		{
//			get
//			{
//				return this._TITLE;
//			}
//			set
//			{
//				if ((this._TITLE != value))
//				{
//					this.OnTITLEChanging(value);
//					this.SendPropertyChanging();
//					this._TITLE = value;
//					this.SendPropertyChanged("TITLE");
//					this.OnTITLEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIRE_DATE", DbType="DateTime NOT NULL")]
//		public System.DateTime HIRE_DATE
//		{
//			get
//			{
//				return this._HIRE_DATE;
//			}
//			set
//			{
//				if ((this._HIRE_DATE != value))
//				{
//					this.OnHIRE_DATEChanging(value);
//					this.SendPropertyChanging();
//					this._HIRE_DATE = value;
//					this.SendPropertyChanged("HIRE_DATE");
//					this.OnHIRE_DATEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANAGER", DbType="Int")]
//		public System.Nullable<int> MANAGER
//		{
//			get
//			{
//				return this._MANAGER;
//			}
//			set
//			{
//				if ((this._MANAGER != value))
//				{
//					if (this._SALESREP1.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnMANAGERChanging(value);
//					this.SendPropertyChanging();
//					this._MANAGER = value;
//					this.SendPropertyChanged("MANAGER");
//					this.OnMANAGERChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUOTA", DbType="Money")]
//		public System.Nullable<decimal> QUOTA
//		{
//			get
//			{
//				return this._QUOTA;
//			}
//			set
//			{
//				if ((this._QUOTA != value))
//				{
//					this.OnQUOTAChanging(value);
//					this.SendPropertyChanging();
//					this._QUOTA = value;
//					this.SendPropertyChanged("QUOTA");
//					this.OnQUOTAChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALES", DbType="Money NOT NULL")]
//		public decimal SALES
//		{
//			get
//			{
//				return this._SALES;
//			}
//			set
//			{
//				if ((this._SALES != value))
//				{
//					this.OnSALESChanging(value);
//					this.SendPropertyChanging();
//					this._SALES = value;
//					this.SendPropertyChanged("SALES");
//					this.OnSALESChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_CUSTOMER", Storage="_CUSTOMERs", ThisKey="EMPL_NUM", OtherKey="CUST_REP")]
//		public EntitySet<CUSTOMER> CUSTOMERs
//		{
//			get
//			{
//				return this._CUSTOMERs;
//			}
//			set
//			{
//				this._CUSTOMERs.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_SALESREP", Storage="_SALESREPs", ThisKey="EMPL_NUM", OtherKey="MANAGER")]
//		public EntitySet<SALESREP> SALESREPs
//		{
//			get
//			{
//				return this._SALESREPs;
//			}
//			set
//			{
//				this._SALESREPs.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_OFFICE", Storage="_OFFICEs", ThisKey="EMPL_NUM", OtherKey="MGR")]
//		public EntitySet<OFFICE> OFFICEs
//		{
//			get
//			{
//				return this._OFFICEs;
//			}
//			set
//			{
//				this._OFFICEs.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_ORDER", Storage="_ORDERs", ThisKey="EMPL_NUM", OtherKey="REP")]
//		public EntitySet<ORDER> ORDERs
//		{
//			get
//			{
//				return this._ORDERs;
//			}
//			set
//			{
//				this._ORDERs.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_SALESREP", Storage="_SALESREP1", ThisKey="MANAGER", OtherKey="EMPL_NUM", IsForeignKey=true)]
//		public SALESREP SALESREP1
//		{
//			get
//			{
//				return this._SALESREP1.Entity;
//			}
//			set
//			{
//				SALESREP previousValue = this._SALESREP1.Entity;
//				if (((previousValue != value) 
//							|| (this._SALESREP1.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._SALESREP1.Entity = null;
//						previousValue.SALESREPs.Remove(this);
//					}
//					this._SALESREP1.Entity = value;
//					if ((value != null))
//					{
//						value.SALESREPs.Add(this);
//						this._MANAGER = value.EMPL_NUM;
//					}
//					else
//					{
//						this._MANAGER = default(Nullable<int>);
//					}
//					this.SendPropertyChanged("SALESREP1");
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OFFICE_SALESREP", Storage="_OFFICE", ThisKey="REP_OFFICE", OtherKey="OFFICE1", IsForeignKey=true, DeleteRule="SET NULL")]
//		public OFFICE OFFICE
//		{
//			get
//			{
//				return this._OFFICE.Entity;
//			}
//			set
//			{
//				OFFICE previousValue = this._OFFICE.Entity;
//				if (((previousValue != value) 
//							|| (this._OFFICE.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._OFFICE.Entity = null;
//						previousValue.SALESREPs.Remove(this);
//					}
//					this._OFFICE.Entity = value;
//					if ((value != null))
//					{
//						value.SALESREPs.Add(this);
//						this._REP_OFFICE = value.OFFICE1;
//					}
//					else
//					{
//						this._REP_OFFICE = default(Nullable<int>);
//					}
//					this.SendPropertyChanged("OFFICE");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_CUSTOMERs(CUSTOMER entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP = this;
//		}
		
//		private void detach_CUSTOMERs(CUSTOMER entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP = null;
//		}
		
//		private void attach_SALESREPs(SALESREP entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP1 = this;
//		}
		
//		private void detach_SALESREPs(SALESREP entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP1 = null;
//		}
		
//		private void attach_OFFICEs(OFFICE entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP = this;
//		}
		
//		private void detach_OFFICEs(OFFICE entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP = null;
//		}
		
//		private void attach_ORDERs(ORDER entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP = this;
//		}
		
//		private void detach_ORDERs(ORDER entity)
//		{
//			this.SendPropertyChanging();
//			entity.SALESREP = null;
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OFFICES")]
//	public partial class OFFICE : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _OFFICE1;
		
//		private string _CITY;
		
//		private string _REGION;
		
//		private System.Nullable<int> _MGR;
		
//		private System.Nullable<decimal> _TARGET;
		
//		private decimal _SALES;
		
//		private EntitySet<SALESREP> _SALESREPs;
		
//		private EntityRef<SALESREP> _SALESREP;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnOFFICE1Changing(int value);
//    partial void OnOFFICE1Changed();
//    partial void OnCITYChanging(string value);
//    partial void OnCITYChanged();
//    partial void OnREGIONChanging(string value);
//    partial void OnREGIONChanged();
//    partial void OnMGRChanging(System.Nullable<int> value);
//    partial void OnMGRChanged();
//    partial void OnTARGETChanging(System.Nullable<decimal> value);
//    partial void OnTARGETChanged();
//    partial void OnSALESChanging(decimal value);
//    partial void OnSALESChanged();
//    #endregion
		
//		public OFFICE()
//		{
//			this._SALESREPs = new EntitySet<SALESREP>(new Action<SALESREP>(this.attach_SALESREPs), new Action<SALESREP>(this.detach_SALESREPs));
//			this._SALESREP = default(EntityRef<SALESREP>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="OFFICE", Storage="_OFFICE1", DbType="Int NOT NULL", IsPrimaryKey=true)]
//		public int OFFICE1
//		{
//			get
//			{
//				return this._OFFICE1;
//			}
//			set
//			{
//				if ((this._OFFICE1 != value))
//				{
//					this.OnOFFICE1Changing(value);
//					this.SendPropertyChanging();
//					this._OFFICE1 = value;
//					this.SendPropertyChanged("OFFICE1");
//					this.OnOFFICE1Changed();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
//		public string CITY
//		{
//			get
//			{
//				return this._CITY;
//			}
//			set
//			{
//				if ((this._CITY != value))
//				{
//					this.OnCITYChanging(value);
//					this.SendPropertyChanging();
//					this._CITY = value;
//					this.SendPropertyChanged("CITY");
//					this.OnCITYChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REGION", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
//		public string REGION
//		{
//			get
//			{
//				return this._REGION;
//			}
//			set
//			{
//				if ((this._REGION != value))
//				{
//					this.OnREGIONChanging(value);
//					this.SendPropertyChanging();
//					this._REGION = value;
//					this.SendPropertyChanged("REGION");
//					this.OnREGIONChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MGR", DbType="Int")]
//		public System.Nullable<int> MGR
//		{
//			get
//			{
//				return this._MGR;
//			}
//			set
//			{
//				if ((this._MGR != value))
//				{
//					if (this._SALESREP.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnMGRChanging(value);
//					this.SendPropertyChanging();
//					this._MGR = value;
//					this.SendPropertyChanged("MGR");
//					this.OnMGRChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARGET", DbType="Money")]
//		public System.Nullable<decimal> TARGET
//		{
//			get
//			{
//				return this._TARGET;
//			}
//			set
//			{
//				if ((this._TARGET != value))
//				{
//					this.OnTARGETChanging(value);
//					this.SendPropertyChanging();
//					this._TARGET = value;
//					this.SendPropertyChanged("TARGET");
//					this.OnTARGETChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALES", DbType="Money NOT NULL")]
//		public decimal SALES
//		{
//			get
//			{
//				return this._SALES;
//			}
//			set
//			{
//				if ((this._SALES != value))
//				{
//					this.OnSALESChanging(value);
//					this.SendPropertyChanging();
//					this._SALES = value;
//					this.SendPropertyChanged("SALES");
//					this.OnSALESChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OFFICE_SALESREP", Storage="_SALESREPs", ThisKey="OFFICE1", OtherKey="REP_OFFICE")]
//		public EntitySet<SALESREP> SALESREPs
//		{
//			get
//			{
//				return this._SALESREPs;
//			}
//			set
//			{
//				this._SALESREPs.Assign(value);
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_OFFICE", Storage="_SALESREP", ThisKey="MGR", OtherKey="EMPL_NUM", IsForeignKey=true, DeleteRule="SET NULL")]
//		public SALESREP SALESREP
//		{
//			get
//			{
//				return this._SALESREP.Entity;
//			}
//			set
//			{
//				SALESREP previousValue = this._SALESREP.Entity;
//				if (((previousValue != value) 
//							|| (this._SALESREP.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._SALESREP.Entity = null;
//						previousValue.OFFICEs.Remove(this);
//					}
//					this._SALESREP.Entity = value;
//					if ((value != null))
//					{
//						value.OFFICEs.Add(this);
//						this._MGR = value.EMPL_NUM;
//					}
//					else
//					{
//						this._MGR = default(Nullable<int>);
//					}
//					this.SendPropertyChanged("SALESREP");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_SALESREPs(SALESREP entity)
//		{
//			this.SendPropertyChanging();
//			entity.OFFICE = this;
//		}
		
//		private void detach_SALESREPs(SALESREP entity)
//		{
//			this.SendPropertyChanging();
//			entity.OFFICE = null;
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ORDERS")]
//	public partial class ORDER : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private int _ORDER_NUM;
		
//		private System.DateTime _ORDER_DATE;
		
//		private int _CUST;
		
//		private System.Nullable<int> _REP;
		
//		private string _MFR;
		
//		private string _PRODUCT;
		
//		private int _QTY;
		
//		private decimal _AMOUNT;
		
//		private EntityRef<CUSTOMER> _CUSTOMER;
		
//		private EntityRef<SALESREP> _SALESREP;
		
//		private EntityRef<PRODUCT> _PRODUCT1;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnORDER_NUMChanging(int value);
//    partial void OnORDER_NUMChanged();
//    partial void OnORDER_DATEChanging(System.DateTime value);
//    partial void OnORDER_DATEChanged();
//    partial void OnCUSTChanging(int value);
//    partial void OnCUSTChanged();
//    partial void OnREPChanging(System.Nullable<int> value);
//    partial void OnREPChanged();
//    partial void OnMFRChanging(string value);
//    partial void OnMFRChanged();
//    partial void OnPRODUCTChanging(string value);
//    partial void OnPRODUCTChanged();
//    partial void OnQTYChanging(int value);
//    partial void OnQTYChanged();
//    partial void OnAMOUNTChanging(decimal value);
//    partial void OnAMOUNTChanged();
//    #endregion
		
//		public ORDER()
//		{
//			this._CUSTOMER = default(EntityRef<CUSTOMER>);
//			this._SALESREP = default(EntityRef<SALESREP>);
//			this._PRODUCT1 = default(EntityRef<PRODUCT>);
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_NUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
//		public int ORDER_NUM
//		{
//			get
//			{
//				return this._ORDER_NUM;
//			}
//			set
//			{
//				if ((this._ORDER_NUM != value))
//				{
//					this.OnORDER_NUMChanging(value);
//					this.SendPropertyChanging();
//					this._ORDER_NUM = value;
//					this.SendPropertyChanged("ORDER_NUM");
//					this.OnORDER_NUMChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORDER_DATE", DbType="DateTime NOT NULL")]
//		public System.DateTime ORDER_DATE
//		{
//			get
//			{
//				return this._ORDER_DATE;
//			}
//			set
//			{
//				if ((this._ORDER_DATE != value))
//				{
//					this.OnORDER_DATEChanging(value);
//					this.SendPropertyChanging();
//					this._ORDER_DATE = value;
//					this.SendPropertyChanged("ORDER_DATE");
//					this.OnORDER_DATEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST", DbType="Int NOT NULL")]
//		public int CUST
//		{
//			get
//			{
//				return this._CUST;
//			}
//			set
//			{
//				if ((this._CUST != value))
//				{
//					if (this._CUSTOMER.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnCUSTChanging(value);
//					this.SendPropertyChanging();
//					this._CUST = value;
//					this.SendPropertyChanged("CUST");
//					this.OnCUSTChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REP", DbType="Int")]
//		public System.Nullable<int> REP
//		{
//			get
//			{
//				return this._REP;
//			}
//			set
//			{
//				if ((this._REP != value))
//				{
//					if (this._SALESREP.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnREPChanging(value);
//					this.SendPropertyChanging();
//					this._REP = value;
//					this.SendPropertyChanged("REP");
//					this.OnREPChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFR", DbType="Char(3) NOT NULL", CanBeNull=false)]
//		public string MFR
//		{
//			get
//			{
//				return this._MFR;
//			}
//			set
//			{
//				if ((this._MFR != value))
//				{
//					if (this._PRODUCT1.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnMFRChanging(value);
//					this.SendPropertyChanging();
//					this._MFR = value;
//					this.SendPropertyChanged("MFR");
//					this.OnMFRChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT", DbType="Char(5) NOT NULL", CanBeNull=false)]
//		public string PRODUCT
//		{
//			get
//			{
//				return this._PRODUCT;
//			}
//			set
//			{
//				if ((this._PRODUCT != value))
//				{
//					if (this._PRODUCT1.HasLoadedOrAssignedValue)
//					{
//						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
//					}
//					this.OnPRODUCTChanging(value);
//					this.SendPropertyChanging();
//					this._PRODUCT = value;
//					this.SendPropertyChanged("PRODUCT");
//					this.OnPRODUCTChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Int NOT NULL")]
//		public int QTY
//		{
//			get
//			{
//				return this._QTY;
//			}
//			set
//			{
//				if ((this._QTY != value))
//				{
//					this.OnQTYChanging(value);
//					this.SendPropertyChanging();
//					this._QTY = value;
//					this.SendPropertyChanged("QTY");
//					this.OnQTYChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AMOUNT", DbType="Money NOT NULL")]
//		public decimal AMOUNT
//		{
//			get
//			{
//				return this._AMOUNT;
//			}
//			set
//			{
//				if ((this._AMOUNT != value))
//				{
//					this.OnAMOUNTChanging(value);
//					this.SendPropertyChanging();
//					this._AMOUNT = value;
//					this.SendPropertyChanged("AMOUNT");
//					this.OnAMOUNTChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_ORDER", Storage="_CUSTOMER", ThisKey="CUST", OtherKey="CUST_NUM", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
//		public CUSTOMER CUSTOMER
//		{
//			get
//			{
//				return this._CUSTOMER.Entity;
//			}
//			set
//			{
//				CUSTOMER previousValue = this._CUSTOMER.Entity;
//				if (((previousValue != value) 
//							|| (this._CUSTOMER.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._CUSTOMER.Entity = null;
//						previousValue.ORDERs.Remove(this);
//					}
//					this._CUSTOMER.Entity = value;
//					if ((value != null))
//					{
//						value.ORDERs.Add(this);
//						this._CUST = value.CUST_NUM;
//					}
//					else
//					{
//						this._CUST = default(int);
//					}
//					this.SendPropertyChanged("CUSTOMER");
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SALESREP_ORDER", Storage="_SALESREP", ThisKey="REP", OtherKey="EMPL_NUM", IsForeignKey=true, DeleteRule="SET NULL")]
//		public SALESREP SALESREP
//		{
//			get
//			{
//				return this._SALESREP.Entity;
//			}
//			set
//			{
//				SALESREP previousValue = this._SALESREP.Entity;
//				if (((previousValue != value) 
//							|| (this._SALESREP.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._SALESREP.Entity = null;
//						previousValue.ORDERs.Remove(this);
//					}
//					this._SALESREP.Entity = value;
//					if ((value != null))
//					{
//						value.ORDERs.Add(this);
//						this._REP = value.EMPL_NUM;
//					}
//					else
//					{
//						this._REP = default(Nullable<int>);
//					}
//					this.SendPropertyChanged("SALESREP");
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_ORDER", Storage="_PRODUCT1", ThisKey="MFR,PRODUCT", OtherKey="MFR_ID,PRODUCT_ID", IsForeignKey=true)]
//		public PRODUCT PRODUCT1
//		{
//			get
//			{
//				return this._PRODUCT1.Entity;
//			}
//			set
//			{
//				PRODUCT previousValue = this._PRODUCT1.Entity;
//				if (((previousValue != value) 
//							|| (this._PRODUCT1.HasLoadedOrAssignedValue == false)))
//				{
//					this.SendPropertyChanging();
//					if ((previousValue != null))
//					{
//						this._PRODUCT1.Entity = null;
//						previousValue.ORDERs.Remove(this);
//					}
//					this._PRODUCT1.Entity = value;
//					if ((value != null))
//					{
//						value.ORDERs.Add(this);
//						this._MFR = value.MFR_ID;
//						this._PRODUCT = value.PRODUCT_ID;
//					}
//					else
//					{
//						this._MFR = default(string);
//						this._PRODUCT = default(string);
//					}
//					this.SendPropertyChanged("PRODUCT1");
//				}
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
//	}
	
//	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PRODUCTS")]
//	public partial class PRODUCT : INotifyPropertyChanging, INotifyPropertyChanged
//	{
		
//		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
//		private string _MFR_ID;
		
//		private string _PRODUCT_ID;
		
//		private string _DESCRIPTION;
		
//		private decimal _PRICE;
		
//		private int _QTY_ON_HAND;
		
//		private EntitySet<ORDER> _ORDERs;
		
//    #region Extensibility Method Definitions
//    partial void OnLoaded();
//    partial void OnValidate(System.Data.Linq.ChangeAction action);
//    partial void OnCreated();
//    partial void OnMFR_IDChanging(string value);
//    partial void OnMFR_IDChanged();
//    partial void OnPRODUCT_IDChanging(string value);
//    partial void OnPRODUCT_IDChanged();
//    partial void OnDESCRIPTIONChanging(string value);
//    partial void OnDESCRIPTIONChanged();
//    partial void OnPRICEChanging(decimal value);
//    partial void OnPRICEChanged();
//    partial void OnQTY_ON_HANDChanging(int value);
//    partial void OnQTY_ON_HANDChanged();
//    #endregion
		
//		public PRODUCT()
//		{
//			this._ORDERs = new EntitySet<ORDER>(new Action<ORDER>(this.attach_ORDERs), new Action<ORDER>(this.detach_ORDERs));
//			OnCreated();
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MFR_ID", DbType="Char(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
//		public string MFR_ID
//		{
//			get
//			{
//				return this._MFR_ID;
//			}
//			set
//			{
//				if ((this._MFR_ID != value))
//				{
//					this.OnMFR_IDChanging(value);
//					this.SendPropertyChanging();
//					this._MFR_ID = value;
//					this.SendPropertyChanged("MFR_ID");
//					this.OnMFR_IDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRODUCT_ID", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
//		public string PRODUCT_ID
//		{
//			get
//			{
//				return this._PRODUCT_ID;
//			}
//			set
//			{
//				if ((this._PRODUCT_ID != value))
//				{
//					this.OnPRODUCT_IDChanging(value);
//					this.SendPropertyChanging();
//					this._PRODUCT_ID = value;
//					this.SendPropertyChanged("PRODUCT_ID");
//					this.OnPRODUCT_IDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPTION", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
//		public string DESCRIPTION
//		{
//			get
//			{
//				return this._DESCRIPTION;
//			}
//			set
//			{
//				if ((this._DESCRIPTION != value))
//				{
//					this.OnDESCRIPTIONChanging(value);
//					this.SendPropertyChanging();
//					this._DESCRIPTION = value;
//					this.SendPropertyChanged("DESCRIPTION");
//					this.OnDESCRIPTIONChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Money NOT NULL")]
//		public decimal PRICE
//		{
//			get
//			{
//				return this._PRICE;
//			}
//			set
//			{
//				if ((this._PRICE != value))
//				{
//					this.OnPRICEChanging(value);
//					this.SendPropertyChanging();
//					this._PRICE = value;
//					this.SendPropertyChanged("PRICE");
//					this.OnPRICEChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY_ON_HAND", DbType="Int NOT NULL")]
//		public int QTY_ON_HAND
//		{
//			get
//			{
//				return this._QTY_ON_HAND;
//			}
//			set
//			{
//				if ((this._QTY_ON_HAND != value))
//				{
//					this.OnQTY_ON_HANDChanging(value);
//					this.SendPropertyChanging();
//					this._QTY_ON_HAND = value;
//					this.SendPropertyChanged("QTY_ON_HAND");
//					this.OnQTY_ON_HANDChanged();
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PRODUCT_ORDER", Storage="_ORDERs", ThisKey="MFR_ID,PRODUCT_ID", OtherKey="MFR,PRODUCT")]
//		public EntitySet<ORDER> ORDERs
//		{
//			get
//			{
//				return this._ORDERs;
//			}
//			set
//			{
//				this._ORDERs.Assign(value);
//			}
//		}
		
//		public event PropertyChangingEventHandler PropertyChanging;
		
//		public event PropertyChangedEventHandler PropertyChanged;
		
//		protected virtual void SendPropertyChanging()
//		{
//			if ((this.PropertyChanging != null))
//			{
//				this.PropertyChanging(this, emptyChangingEventArgs);
//			}
//		}
		
//		protected virtual void SendPropertyChanged(String propertyName)
//		{
//			if ((this.PropertyChanged != null))
//			{
//				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
//			}
//		}
		
//		private void attach_ORDERs(ORDER entity)
//		{
//			this.SendPropertyChanging();
//			entity.PRODUCT1 = this;
//		}
		
//		private void detach_ORDERs(ORDER entity)
//		{
//			this.SendPropertyChanging();
//			entity.PRODUCT1 = null;
//		}
//	}
	
//	public partial class spCustomerByNameResult
//	{
		
//		private int _CUST_NUM;
		
//		private string _COMPANY;
		
//		private System.Nullable<int> _CUST_REP;
		
//		private System.Nullable<decimal> _CREDIT_LIMIT;
		
//		public spCustomerByNameResult()
//		{
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NUM", DbType="Int NOT NULL")]
//		public int CUST_NUM
//		{
//			get
//			{
//				return this._CUST_NUM;
//			}
//			set
//			{
//				if ((this._CUST_NUM != value))
//				{
//					this._CUST_NUM = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
//		public string COMPANY
//		{
//			get
//			{
//				return this._COMPANY;
//			}
//			set
//			{
//				if ((this._COMPANY != value))
//				{
//					this._COMPANY = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REP", DbType="Int")]
//		public System.Nullable<int> CUST_REP
//		{
//			get
//			{
//				return this._CUST_REP;
//			}
//			set
//			{
//				if ((this._CUST_REP != value))
//				{
//					this._CUST_REP = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDIT_LIMIT", DbType="Money")]
//		public System.Nullable<decimal> CREDIT_LIMIT
//		{
//			get
//			{
//				return this._CREDIT_LIMIT;
//			}
//			set
//			{
//				if ((this._CREDIT_LIMIT != value))
//				{
//					this._CREDIT_LIMIT = value;
//				}
//			}
//		}
//	}
	
//	public partial class spCustomerByName2Result
//	{
		
//		private int _CUST_NUM;
		
//		private string _COMPANY;
		
//		private System.Nullable<int> _CUST_REP;
		
//		private System.Nullable<decimal> _CREDIT_LIMIT;
		
//		public spCustomerByName2Result()
//		{
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NUM", DbType="Int NOT NULL")]
//		public int CUST_NUM
//		{
//			get
//			{
//				return this._CUST_NUM;
//			}
//			set
//			{
//				if ((this._CUST_NUM != value))
//				{
//					this._CUST_NUM = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
//		public string COMPANY
//		{
//			get
//			{
//				return this._COMPANY;
//			}
//			set
//			{
//				if ((this._COMPANY != value))
//				{
//					this._COMPANY = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REP", DbType="Int")]
//		public System.Nullable<int> CUST_REP
//		{
//			get
//			{
//				return this._CUST_REP;
//			}
//			set
//			{
//				if ((this._CUST_REP != value))
//				{
//					this._CUST_REP = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDIT_LIMIT", DbType="Money")]
//		public System.Nullable<decimal> CREDIT_LIMIT
//		{
//			get
//			{
//				return this._CREDIT_LIMIT;
//			}
//			set
//			{
//				if ((this._CREDIT_LIMIT != value))
//				{
//					this._CREDIT_LIMIT = value;
//				}
//			}
//		}
//	}
	
//	public partial class sfCustomerInfoByIdResult
//	{
		
//		private int _CUST_NUM;
		
//		private string _COMPANY;
		
//		private System.Nullable<int> _CUST_REP;
		
//		private System.Nullable<decimal> _CREDIT_LIMIT;
		
//		public sfCustomerInfoByIdResult()
//		{
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_NUM", DbType="Int NOT NULL")]
//		public int CUST_NUM
//		{
//			get
//			{
//				return this._CUST_NUM;
//			}
//			set
//			{
//				if ((this._CUST_NUM != value))
//				{
//					this._CUST_NUM = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANY", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
//		public string COMPANY
//		{
//			get
//			{
//				return this._COMPANY;
//			}
//			set
//			{
//				if ((this._COMPANY != value))
//				{
//					this._COMPANY = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUST_REP", DbType="Int")]
//		public System.Nullable<int> CUST_REP
//		{
//			get
//			{
//				return this._CUST_REP;
//			}
//			set
//			{
//				if ((this._CUST_REP != value))
//				{
//					this._CUST_REP = value;
//				}
//			}
//		}
		
//		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDIT_LIMIT", DbType="Money")]
//		public System.Nullable<decimal> CREDIT_LIMIT
//		{
//			get
//			{
//				return this._CREDIT_LIMIT;
//			}
//			set
//			{
//				if ((this._CREDIT_LIMIT != value))
//				{
//					this._CREDIT_LIMIT = value;
//				}
//			}
//		}
//	}
//}
//#pragma warning restore 1591
