//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTest._21_Database._02_EntityFramework._01_DatabaseFirst
{
    using System;

    public partial class Orders2
    {
        public int onum { get; set; }
        public Nullable<decimal> amt { get; set; }
        public System.DateTime odate { get; set; }
        public int cnum { get; set; }
        public int snum { get; set; }
    
        public virtual Customers2 Customers2 { get; set; }
        public virtual Salespeople Salespeople { get; set; }
    }
}
