//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTest._21_Database._02_EntityFramework._01_DatabaseFirst
{
    using System;

    public partial class ORDERS
    {
        public int ORDER_NUM { get; set; }
        public System.DateTime ORDER_DATE { get; set; }
        public int CUST { get; set; }
        public Nullable<int> REP { get; set; }
        public string MFR { get; set; }
        public string PRODUCT { get; set; }
        public int QTY { get; set; }
        public decimal AMOUNT { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual PRODUCTS PRODUCTS { get; set; }
        public virtual SALESREPS SALESREPS { get; set; }
    }
}
