<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="10_SelectEditDelete.aspx.cs"
    Inherits="ASPWebFormsTest._08_DataBinding._09_GridView._10_SelectEditDelete" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" CellPadding="4"
                DataKeyNames="ProductID" DataSourceID="NorthwindDataSource" ForeColor="#333333"
                GridLines="None"
                AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True"
                AutoGenerateSelectButton="True">

                <%--Настройка колонок--%>
                <Columns>
                    <asp:BoundField DataField="ProductID" HeaderText="Product ID" InsertVisible="False" ReadOnly="True" SortExpression="ProductID" />
                    <asp:BoundField DataField="ProductName" HeaderText="Product Name" SortExpression="ProductName" />
                    <asp:BoundField DataField="UnitPrice" HeaderText="Unit Price" SortExpression="UnitPrice" />
                    <asp:BoundField DataField="UnitsOnOrder" HeaderText="Units On Order" SortExpression="UnitsOnOrder" />
                    <asp:BoundField DataField="QuantityPerUnit" HeaderText="Quantity Per Unit" SortExpression="QuantityPerUnit" />
                </Columns>

                <%--Настройка стиля--%>
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
            </asp:GridView>

            <%--Источник данных--%>
            <asp:SqlDataSource ID="NorthwindDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:NorthwindConnection %>"
                SelectCommand="SELECT [ProductName], [UnitPrice], [UnitsOnOrder], [QuantityPerUnit], [ProductID] FROM [Products]" DeleteCommand="DELETE FROM [Products] WHERE [ProductID] = @ProductID"
                InsertCommand="INSERT INTO [Products] ([ProductName], [UnitPrice], [UnitsOnOrder], [QuantityPerUnit]) VALUES (@ProductName, @UnitPrice, @UnitsOnOrder, @QuantityPerUnit)"
                UpdateCommand="UPDATE [Products] SET [ProductName] = @ProductName, [UnitPrice] = @UnitPrice, [UnitsOnOrder] = @UnitsOnOrder, [QuantityPerUnit] = @QuantityPerUnit WHERE [ProductID] = @ProductID">
                <DeleteParameters>
                    <asp:Parameter Name="ProductID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="ProductName" Type="String" />
                    <asp:Parameter Name="UnitPrice" Type="Decimal" />
                    <asp:Parameter Name="UnitsOnOrder" Type="Int16" />
                    <asp:Parameter Name="QuantityPerUnit" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="ProductName" Type="String" />
                    <asp:Parameter Name="UnitPrice" Type="Decimal" />
                    <asp:Parameter Name="UnitsOnOrder" Type="Int16" />
                    <asp:Parameter Name="QuantityPerUnit" Type="String" />
                    <asp:Parameter Name="ProductID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
