DROP TABLE "REL_AUTH_BOOK"
/
DROP TABLE "AUTHOR"
/
DROP TABLE "ORDERS"
/
CREATE TABLE  "AUTHOR" 
   ("ID" NUMBER(3,0) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT "AUTHOR_PK" PRIMARY KEY ("ID") ENABLE
   )
/
DROP SEQUENCE "AUTHOR_SEQ"
/
CREATE SEQUENCE "AUTHOR_SEQ"
/
DROP TABLE "BOOK"
/
CREATE TABLE  "BOOK" 
   ("ID" NUMBER(3,0) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "BOOK_PK" PRIMARY KEY ("ID") ENABLE
   )
/
DROP SEQUENCE "BOOK_SEQ"
/
CREATE SEQUENCE "BOOK_SEQ"
/
DROP TABLE "ORDERS"
/
CREATE TABLE  "ORDERS" 
   ("ID" NUMBER(3,0) NOT NULL ENABLE, 
	"SUBSCRIBER_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"BOOK_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"DATESTART" TIMESTAMP (6) NOT NULL ENABLE, 
	"DATEEND" TIMESTAMP (6), 
	"ACTIVITY" NUMBER(1,0) NOT NULL ENABLE, 
	 CONSTRAINT "ORDERS_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "ORDERS_FK" FOREIGN KEY ("SUBSCRIBER_ID")
	 REFERENCES  "SUBSCRIBER" ("ID") ENABLE, 
	 CONSTRAINT "ORDERS_FK2" FOREIGN KEY ("BOOK_ID")
	 REFERENCES  "BOOK" ("ID") ENABLE
   )
/
DROP SEQUENCE "ORDERS_SEQ"
/
CREATE SEQUENCE "ORDERS_SEQ"
/
DROP TABLE "REL_AUTH_BOOK"
/
CREATE TABLE  "REL_AUTH_BOOK" 
   ("AUTHOR_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"BOOK_ID" NUMBER(3,0) NOT NULL ENABLE,
	 CONSTRAINT "REL_AUTH_BOOK_PK" PRIMARY KEY ("AUTHOR_ID", "BOOK_ID") ENABLE, 
	 CONSTRAINT "REL_AUTH_BOOK_FK" FOREIGN KEY ("AUTHOR_ID")
	 REFERENCES  "AUTHOR" ("ID") ENABLE, 
	 CONSTRAINT "REL_AUTH_BOOK_FK2" FOREIGN KEY ("BOOK_ID")
	 REFERENCES  "BOOK" ("ID") ENABLE
   )
/
DROP TABLE "SUBSCRIBER"
/
CREATE TABLE  "SUBSCRIBER" 
   (	"ID" NUMBER(3,0) NOT NULL ENABLE, 
	"SURNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"NAME" VARCHAR2(25) NOT NULL ENABLE, 
	 CONSTRAINT "SUBSCRIBER_PK" PRIMARY KEY ("ID") ENABLE
   )
/
DROP SEQUENCE "SUBSCRIBER_SEQ"
/
CREATE SEQUENCE "SUBSCRIBER_SEQ"