//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTest._21_Database._02_EntityFramework._01_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Employees1 = new HashSet<Employees>();
        }
    
        public int empno { get; set; }
        public string name { get; set; }
        public Nullable<int> manager { get; set; }
    
        public virtual ICollection<Employees> Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
    }
}
