//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTest._21_Database._02_EntityFramework._01_DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICES
    {
        public OFFICES()
        {
            this.SALESREPS1 = new HashSet<SALESREPS>();
        }
    
        public int OFFICE { get; set; }
        public string CITY { get; set; }
        public string REGION { get; set; }
        public Nullable<int> MGR { get; set; }
        public Nullable<decimal> TARGET { get; set; }
        public decimal SALES { get; set; }
    
        public virtual SALESREPS SALESREPS { get; set; }
        public virtual ICollection<SALESREPS> SALESREPS1 { get; set; }
    }
}
