//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSTest._21_Database._02_EntityFramework._01_DatabaseFirst
{
    using System.Collections.Generic;

    public partial class PRODUCTS
    {
        public PRODUCTS()
        {
            this.ORDERS = new HashSet<ORDERS>();
        }
    
        public string MFR_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }
        public int QTY_ON_HAND { get; set; }
    
        public virtual ICollection<ORDERS> ORDERS { get; set; }
    }
}
